// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfAwnSoc5clVLp_cKdckMEjPRB1K8rE1I',
    appId: '1:8182076841:web:ffb2e5231c81bf562060b8',
    messagingSenderId: '8182076841',
    projectId: 'finalcrud-5d602',
    authDomain: 'finalcrud-5d602.firebaseapp.com',
    storageBucket: 'finalcrud-5d602.firebasestorage.app',
    measurementId: 'G-PJBZ1E8JNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx1Fg84ijmW-8mmsUKlqBlOwXInKIT_oY',
    appId: '1:8182076841:android:80bf06420053d08f2060b8',
    messagingSenderId: '8182076841',
    projectId: 'finalcrud-5d602',
    storageBucket: 'finalcrud-5d602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD40POAUh-tKVovDXxWJDKEtMDTqT7P-go',
    appId: '1:8182076841:ios:f9a4d656601280de2060b8',
    messagingSenderId: '8182076841',
    projectId: 'finalcrud-5d602',
    storageBucket: 'finalcrud-5d602.firebasestorage.app',
    iosBundleId: 'com.example.webView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD40POAUh-tKVovDXxWJDKEtMDTqT7P-go',
    appId: '1:8182076841:ios:f9a4d656601280de2060b8',
    messagingSenderId: '8182076841',
    projectId: 'finalcrud-5d602',
    storageBucket: 'finalcrud-5d602.firebasestorage.app',
    iosBundleId: 'com.example.webView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfAwnSoc5clVLp_cKdckMEjPRB1K8rE1I',
    appId: '1:8182076841:web:3720f131eaee89a62060b8',
    messagingSenderId: '8182076841',
    projectId: 'finalcrud-5d602',
    authDomain: 'finalcrud-5d602.firebaseapp.com',
    storageBucket: 'finalcrud-5d602.firebasestorage.app',
    measurementId: 'G-V5QDZQRWKH',
  );
}
